config/routes.rb
SteelfitProject::Application.routes.draw do
  get "welcome/index"

  resources :grocerylists
  
  root 'welcome#index'

end

app/models/grocerylist.rb
class Grocerylist < ActiveRecord::Base
  validates :user, presence: true, length: { minimum: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grocerylists_controller.rb
class GrocerylistsController < ApplicationController
  def index
    @grocerylists = Grocerylist.all
  end

  def show
	@grocerylist = Grocerylist.find(params[:id])
  end
  
  def new
	@grocerylist = Grocerylist.new
  end
  
  def edit
    @grocerylist = Grocerylist.find(params[:id])
  end
  
  def create
    @grocerylist = Grocerylist.new(grocerylist_params)
	if @grocerylist.save
      redirect_to @grocerylist
	else
	  render 'new'
    end
  end
  
  def update
    @grocerylist = Grocerylist.find(params[:id])
    if @grocerylist.update(grocerylist_params)
		redirect_to @grocerylist
	else
		render 'edit'
	end
  end

  def destroy
	@grocerylist = Grocerylist.find(params[:id])
	@grocerylist.destroy!
	redirect_to grocerylists_path
  end
  
  private
	def grocerylist_params
		params.require(:grocerylist).permit(:user, :grocerylist)
	end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grocerylists_helper.rb
module GrocerylistsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/grocerylists/edit.html.erb
<h1>Editing grocerylist</h1>

<%= form_for :grocerylist, url: grocerylist_path(@grocerylist), method: :patch do |f| %>

  <% if @grocerylist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@grocerylist.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @grocerylist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </p>
 
  <p>
    <%= f.label :grocerylist, 'Grocery List' %><br>
    <%= f.text_area(:grocerylist, size: "40x10") %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', grocerylists_path %>

app/views/grocerylists/index.html.erb
<%= javascript_include_tag 'jquery_ujs' %>
<h1>Listing All Grocery Lists</h1>
<%= link_to 'Create a new grocery list', new_grocerylist_path %>
 
<table>
  <tr>
    <th>User</th>
    <th>Grocery List</th>
	<th colspan="3"></th>
  </tr>
 
  <% @grocerylists.each do |grocerylist| %>
    <tr>
      <td><%= grocerylist.user %></td>
      <td><%= grocerylist.grocerylist %></td>
      <td><%= link_to 'Show', grocerylist_path(grocerylist) %></td>
      <td><%= link_to 'Edit', edit_grocerylist_path(grocerylist) %></td>
      <td><%= link_to 'Destroy', grocerylist_path(grocerylist), :method => :delete, :onclick => "return confirm('Are you sure you want to delete this post?')"%></td>
    </tr>
  <% end %>
</table>

app/views/grocerylists/new.html.erb
<%= form_for :grocerylist, url: grocerylists_path do |f| %>

  <% if @grocerylist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@grocerylist.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @grocerylist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <p>
    <%= f.label :user %><br>
    <%= f.text_field :user, :value => "Todd Shelton" %>
  </p>
 
  <p>
    <%= f.label :grocerylist, 'Grocery List' %><br>
    <%= f.text_area(:grocerylist, :value => "ingrediant 1
ingrediant 2
ingrediant 3
ingrediant 4", size: "40x10") %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', grocerylists_path %>

app/views/grocerylists/show.html.erb
<p>
  <strong>User:</strong>
  <%= @grocerylist.user %>
</p> 
<p>
  <strong>Grocery list:</strong><br>
  <%= text_area_tag(:grocerylist, @grocerylist.grocerylist, size: "40x10", disabled: true ) %>
</p>

<%= link_to 'Back', grocerylists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SteelfitProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "defaults", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>This is the welcome screen for the Steelfit Project</h1>
<p>There should be some basic info here about what the site
does and maybe some basic recipe information<br>
Should contain search by ingredient and login<br> 
After login would come back to this page</p>

<%= link_to 'My grocerylist', controller: 'grocerylists' %>